<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SatDetail extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::create('audit_sat',function(Blueprint $table){
                $table->string('id')->nullable()->primary();
                $table->string('kode_pdam')->nullable();
                $table->string('nama_pdam')->nullable();
                $table->string('kode_daerah',4)->nullable();
                $table->float('kategori_pdam_kode')->nullable();
                $table->float('kategori_pdam_kode_self')->nullable();

                $table->string('kategori_pdam')->nullable();
                $table->string('kategori_pdam_self')->nullable();

                $table->integer('period_bulan_awal')->nullable();
                $table->integer('period_bulan_ahir')->nullable();
                $table->integer('period_tahun')->nullable();
                $table->dateTime("periode_laporan")->nullable();
                $table->dateTime('updated_input_at')->nullable();
                $table->text('keterangan')->nullable();
                $table->string('verifikasi_provinsi')->nullable();
                $table->string('verifikasi_regional')->nullable();
                $table->string('verifikasi_satker')->nullable();
                $table->integer("sat_nilai_kinerja_ttl_dr_bppspam_tahun")->nullable();
                $table->double("sat_nilai_kinerja_ttl_dr_bppspam_nilai",20,3)->nullable();
                $table->string("sat_nilai_kinerja_ttl_dr_bppspam_satuan")->nullable();
                $table->text("sat_nilai_kinerja_ttl_dr_bppspam_ket")->nullable();
                $table->integer("sat_nilai_aspek_keuangan_dr_bppspam_tahun")->nullable();
                $table->double("sat_nilai_aspek_keuangan_dr_bppspam_nilai",20,3)->nullable();
                $table->string("sat_nilai_aspek_keuangan_dr_bppspam_satuan")->nullable();
                $table->text("sat_nilai_aspek_keuangan_dr_bppspam_ket")->nullable();
                $table->integer("sat_nilai_aspek_pel_dr_bppspam_tahun")->nullable();
                $table->double("sat_nilai_aspek_pel_dr_bppspam_nilai",20,3)->nullable();
                $table->string("sat_nilai_aspek_pel_dr_bppspam_satuan")->nullable();
                $table->text("sat_nilai_aspek_pel_dr_bppspam_ket")->nullable();
                $table->integer("sat_nilai_aspek_operasional_dr_bppspam_tahun")->nullable();
                $table->double("sat_nilai_aspek_operasional_dr_bppspam_nilai",20,3)->nullable();
                $table->string("sat_nilai_aspek_operasional_dr_bppspam_satuan")->nullable();
                $table->text("sat_nilai_aspek_operasional_dr_bppspam_ket")->nullable();
                $table->integer("sat_nilai_aspek_sdm_dr_bppspam_tahun")->nullable();
                $table->double("sat_nilai_aspek_sdm_dr_bppspam_nilai",20,3)->nullable();
                $table->string("sat_nilai_aspek_sdm_dr_bppspam_satuan")->nullable();
                $table->text("sat_nilai_aspek_sdm_dr_bppspam_ket")->nullable();
                $table->integer("sat_status_kinerja_pdam_tahun_sbl_tahun")->nullable();
                $table->double("sat_status_kinerja_pdam_tahun_sbl_nilai",20,3)->nullable();
                $table->string("sat_status_kinerja_pdam_tahun_sbl_satuan")->nullable();
                $table->text("sat_status_kinerja_pdam_tahun_sbl_ket")->nullable();
                $table->integer("sat_status_kinerja_pdam_2_tahun_sbl_tahun")->nullable();
                $table->double("sat_status_kinerja_pdam_2_tahun_sbl_nilai",20,3)->nullable();
                $table->string("sat_status_kinerja_pdam_2_tahun_sbl_satuan")->nullable();
                $table->text("sat_status_kinerja_pdam_2_tahun_sbl_ket")->nullable();
                $table->integer("sat_status_kinerja_pdam_3_tahun_sbl_tahun")->nullable();
                $table->double("sat_status_kinerja_pdam_3_tahun_sbl_nilai",20,3)->nullable();
                $table->string("sat_status_kinerja_pdam_3_tahun_sbl_satuan")->nullable();
                $table->text("sat_status_kinerja_pdam_3_tahun_sbl_ket")->nullable();
                $table->integer("sat_jumlah_pd_di_wilayah_administratif_tahun")->nullable();
                $table->double("sat_jumlah_pd_di_wilayah_administratif_nilai",20,3)->nullable();
                $table->string("sat_jumlah_pd_di_wilayah_administratif_satuan")->nullable();
                $table->text("sat_jumlah_pd_di_wilayah_administratif_ket")->nullable();
                $table->integer("sat_jumlah_pd_di_wilayah_pel_teknis_tahun")->nullable();
                $table->double("sat_jumlah_pd_di_wilayah_pel_teknis_nilai",20,3)->nullable();
                $table->string("sat_jumlah_pd_di_wilayah_pel_teknis_satuan")->nullable();
                $table->text("sat_jumlah_pd_di_wilayah_pel_teknis_ket")->nullable();
                $table->integer("sat_jumlah_pd_trl_tahun")->nullable();
                $table->double("sat_jumlah_pd_trl_nilai",20,3)->nullable();
                $table->string("sat_jumlah_pd_trl_satuan")->nullable();
                $table->text("sat_jumlah_pd_trl_ket")->nullable();
                $table->integer("sat_jumlah_jiwa_per_keluarga_data_bps_tahun")->nullable();
                $table->double("sat_jumlah_jiwa_per_keluarga_data_bps_nilai",20,3)->nullable();
                $table->string("sat_jumlah_jiwa_per_keluarga_data_bps_satuan")->nullable();
                $table->text("sat_jumlah_jiwa_per_keluarga_data_bps_ket")->nullable();
                $table->integer("sat_jumlah_pelanggan_ttl_tahun")->nullable();
                $table->double("sat_jumlah_pelanggan_ttl_nilai",20,3)->nullable();
                $table->string("sat_jumlah_pelanggan_ttl_satuan")->nullable();
                $table->text("sat_jumlah_pelanggan_ttl_ket")->nullable();
                $table->integer("sat_jumlah_sam_baru_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_jumlah_sam_baru_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_jumlah_sam_baru_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_jumlah_sam_baru_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_jumlah_sam_rumah_tangga_tahun")->nullable();
                $table->double("sat_jumlah_sam_rumah_tangga_nilai",20,3)->nullable();
                $table->string("sat_jumlah_sam_rumah_tangga_satuan")->nullable();
                $table->text("sat_jumlah_sam_rumah_tangga_ket")->nullable();
                $table->integer("sat_jumlah_sistem_yg_beroperasi_tahun")->nullable();
                $table->double("sat_jumlah_sistem_yg_beroperasi_nilai",20,3)->nullable();
                $table->string("sat_jumlah_sistem_yg_beroperasi_satuan")->nullable();
                $table->text("sat_jumlah_sistem_yg_beroperasi_ket")->nullable();
                $table->integer("sat_jumlah_ikk_atau_cabang_yg_diop_tahun")->nullable();
                $table->double("sat_jumlah_ikk_atau_cabang_yg_diop_nilai",20,3)->nullable();
                $table->string("sat_jumlah_ikk_atau_cabang_yg_diop_satuan")->nullable();
                $table->text("sat_jumlah_ikk_atau_cabang_yg_diop_ket")->nullable();
                $table->integer("sat_volume_air_yg_diproduksi_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_volume_air_yg_diproduksi_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_volume_air_yg_diproduksi_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_volume_air_yg_diproduksi_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_apakah_tersedia_meter_induk_tahun")->nullable();
                $table->double("sat_apakah_tersedia_meter_induk_nilai",20,3)->nullable();
                $table->string("sat_apakah_tersedia_meter_induk_satuan")->nullable();
                $table->text("sat_apakah_tersedia_meter_induk_ket")->nullable();
                $table->integer("sat_volume_air_yg_dds_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_volume_air_yg_dds_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_volume_air_yg_dds_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_volume_air_yg_dds_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_volume_air_yg_terjual_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_volume_air_yg_terjual_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_volume_air_yg_terjual_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_volume_air_yg_terjual_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_kapasitas_pengambilan_air_baku_tahun")->nullable();
                $table->double("sat_kapasitas_pengambilan_air_baku_nilai",20,3)->nullable();
                $table->string("sat_kapasitas_pengambilan_air_baku_satuan")->nullable();
                $table->text("sat_kapasitas_pengambilan_air_baku_ket")->nullable();
                $table->integer("sat_kapasitas_produksi_air_yg_terpasang_tahun")->nullable();
                $table->double("sat_kapasitas_produksi_air_yg_terpasang_nilai",20,3)->nullable();
                $table->string("sat_kapasitas_produksi_air_yg_terpasang_satuan")->nullable();
                $table->text("sat_kapasitas_produksi_air_yg_terpasang_ket")->nullable();
                $table->integer("sat_jam_operasional_pel_ratarata_tahun")->nullable();
                $table->double("sat_jam_operasional_pel_ratarata_nilai",20,3)->nullable();
                $table->string("sat_jam_operasional_pel_ratarata_satuan")->nullable();
                $table->text("sat_jam_operasional_pel_ratarata_ket")->nullable();
                $table->integer("sat_ttl_pemakaian_lstrk_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_ttl_pemakaian_lstrk_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_ttl_pemakaian_lstrk_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_ttl_pemakaian_lstrk_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_ttl_pemakaian_bbm_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_ttl_pemakaian_bbm_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_ttl_pemakaian_bbm_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_ttl_pemakaian_bbm_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_ttl_by_lstrk_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_ttl_by_lstrk_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_ttl_by_lstrk_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_ttl_by_lstrk_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_tarif_lstrk_pln_u_pdam_tahun")->nullable();
                $table->double("sat_tarif_lstrk_pln_u_pdam_nilai",20,3)->nullable();
                $table->string("sat_tarif_lstrk_pln_u_pdam_satuan")->nullable();
                $table->text("sat_tarif_lstrk_pln_u_pdam_ket")->nullable();
                $table->integer("sat_ttl_by_bbm_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_ttl_by_bbm_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_ttl_by_bbm_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_ttl_by_bbm_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_hg_bbm_tahun")->nullable();
                $table->double("sat_hg_bbm_nilai",20,3)->nullable();
                $table->string("sat_hg_bbm_satuan")->nullable();
                $table->text("sat_hg_bbm_ket")->nullable();
                $table->integer("sat_ttl_by_usaha_tanpa_pensut_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_ttl_by_usaha_tanpa_pensut_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_ttl_by_usaha_tanpa_pensut_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_ttl_by_usaha_tanpa_pensut_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_ttl_by_usaha_dg_pensut_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_ttl_by_usaha_dg_pensut_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_ttl_by_usaha_dg_pensut_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_ttl_by_usaha_dg_pensut_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_tarif_air_ratarata_tahun")->nullable();
                $table->double("sat_tarif_air_ratarata_nilai",20,3)->nullable();
                $table->string("sat_tarif_air_ratarata_satuan")->nullable();
                $table->text("sat_tarif_air_ratarata_ket")->nullable();
                $table->integer("sat_pdpt_air_data_rek_ditagih_kum_slm_prd_lap_tahun")->nullable();
                $table->double("sat_pdpt_air_data_rek_ditagih_kum_slm_prd_lap_nilai",20,3)->nullable();
                $table->string("sat_pdpt_air_data_rek_ditagih_kum_slm_prd_lap_satuan")->nullable();
                $table->text("sat_pdpt_air_data_rek_ditagih_kum_slm_prd_lap_ket")->nullable();
                $table->integer("sat_penerimaan_dr_pjl_air_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_penerimaan_dr_pjl_air_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_penerimaan_dr_pjl_air_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_penerimaan_dr_pjl_air_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_pdpt_yg_ln_kum_slm_per_lap_tahun")->nullable();
                $table->double("sat_pdpt_yg_ln_kum_slm_per_lap_nilai",20,3)->nullable();
                $table->string("sat_pdpt_yg_ln_kum_slm_per_lap_satuan")->nullable();
                $table->text("sat_pdpt_yg_ln_kum_slm_per_lap_ket")->nullable();
                $table->integer("sat_apakah_pemda_mempunyai_rispam_tahun")->nullable();
                $table->double("sat_apakah_pemda_mempunyai_rispam_nilai",20,3)->nullable();
                $table->string("sat_apakah_pemda_mempunyai_rispam_satuan")->nullable();
                $table->text("sat_apakah_pemda_mempunyai_rispam_ket")->nullable();
                $table->integer("sat_tahun_rispam_diterbitkan_tahun")->nullable();
                $table->double("sat_tahun_rispam_diterbitkan_nilai",20,3)->nullable();
                $table->string("sat_tahun_rispam_diterbitkan_satuan")->nullable();
                $table->text("sat_tahun_rispam_diterbitkan_ket")->nullable();
                $table->integer("sat_lamanya_masa_berlaku_rispam_tahun")->nullable();
                $table->double("sat_lamanya_masa_berlaku_rispam_nilai",20,3)->nullable();
                $table->string("sat_lamanya_masa_berlaku_rispam_satuan")->nullable();
                $table->text("sat_lamanya_masa_berlaku_rispam_ket")->nullable();
                $table->integer("sat_apakah_pemda_sedang_menyiapkan_rispam_tahun")->nullable();
                $table->double("sat_apakah_pemda_sedang_menyiapkan_rispam_nilai",20,3)->nullable();
                $table->string("sat_apakah_pemda_sedang_menyiapkan_rispam_satuan")->nullable();
                $table->text("sat_apakah_pemda_sedang_menyiapkan_rispam_ket")->nullable();
                $table->integer("sat_tahun_rispam_akan_diterbitkan_tahun")->nullable();
                $table->double("sat_tahun_rispam_akan_diterbitkan_nilai",20,3)->nullable();
                $table->string("sat_tahun_rispam_akan_diterbitkan_satuan")->nullable();
                $table->text("sat_tahun_rispam_akan_diterbitkan_ket")->nullable();
                $table->integer("sat_jumlah_pd_proyeksi_di_tahun_tg_dlm_rispam_tahun")->nullable();
                $table->double("sat_jumlah_pd_proyeksi_di_tahun_tg_dlm_rispam_nilai",20,3)->nullable();
                $table->string("sat_jumlah_pd_proyeksi_di_tahun_tg_dlm_rispam_satuan")->nullable();
                $table->text("sat_jumlah_pd_proyeksi_di_tahun_tg_dlm_rispam_ket")->nullable();
                $table->integer("sat_tg_pop_yg_akan_trl_dg_jar_ppp_tahun")->nullable();
                $table->double("sat_tg_pop_yg_akan_trl_dg_jar_ppp_nilai",20,3)->nullable();
                $table->string("sat_tg_pop_yg_akan_trl_dg_jar_ppp_satuan")->nullable();
                $table->text("sat_tg_pop_yg_akan_trl_dg_jar_ppp_ket")->nullable();
                $table->integer("sat_tg_pop_yg_akan_trl_dg_jar_bkn_ppp_tahun")->nullable();
                $table->double("sat_tg_pop_yg_akan_trl_dg_jar_bkn_ppp_nilai",20,3)->nullable();
                $table->string("sat_tg_pop_yg_akan_trl_dg_jar_bkn_ppp_satuan")->nullable();
                $table->text("sat_tg_pop_yg_akan_trl_dg_jar_bkn_ppp_ket")->nullable();
                $table->integer("sat_tg_cakupan_pel_jar_ppp_di_tahun_tg_tahun")->nullable();
                $table->double("sat_tg_cakupan_pel_jar_ppp_di_tahun_tg_nilai",20,3)->nullable();
                $table->string("sat_tg_cakupan_pel_jar_ppp_di_tahun_tg_satuan")->nullable();
                $table->text("sat_tg_cakupan_pel_jar_ppp_di_tahun_tg_ket")->nullable();
                $table->integer("sat_tg_cakupan_pel_jar_bkn_ppp_di_tahun_tg_tahun")->nullable();
                $table->double("sat_tg_cakupan_pel_jar_bkn_ppp_di_tahun_tg_nilai",20,3)->nullable();
                $table->string("sat_tg_cakupan_pel_jar_bkn_ppp_di_tahun_tg_satuan")->nullable();
                $table->text("sat_tg_cakupan_pel_jar_bkn_ppp_di_tahun_tg_ket")->nullable();
                $table->integer("sat_alk_apbd_u_penyertaan_modal_pdam_tahun")->nullable();
                $table->double("sat_alk_apbd_u_penyertaan_modal_pdam_nilai",20,3)->nullable();
                $table->string("sat_alk_apbd_u_penyertaan_modal_pdam_satuan")->nullable();
                $table->text("sat_alk_apbd_u_penyertaan_modal_pdam_ket")->nullable();
                $table->integer("sat_alk_dak_u_pny_air_minum_tahun")->nullable();
                $table->double("sat_alk_dak_u_pny_air_minum_nilai",20,3)->nullable();
                $table->string("sat_alk_dak_u_pny_air_minum_satuan")->nullable();
                $table->text("sat_alk_dak_u_pny_air_minum_ket")->nullable();
                $table->integer("sat_alk_apbd_lainnya_u_pny_air_minum_tahun")->nullable();
                $table->double("sat_alk_apbd_lainnya_u_pny_air_minum_nilai",20,3)->nullable();
                $table->string("sat_alk_apbd_lainnya_u_pny_air_minum_satuan")->nullable();
                $table->text("sat_alk_apbd_lainnya_u_pny_air_minum_ket")->nullable();
                $table->integer("sat_jumlah_ttl_apbd_pemda_tahun")->nullable();
                $table->double("sat_jumlah_ttl_apbd_pemda_nilai",20,3)->nullable();
                $table->string("sat_jumlah_ttl_apbd_pemda_satuan")->nullable();
                $table->text("sat_jumlah_ttl_apbd_pemda_ket")->nullable();
                $table->integer("sat_kapasitas_fkl_pemda_tahun")->nullable();
                $table->double("sat_kapasitas_fkl_pemda_nilai",20,3)->nullable();
                $table->string("sat_kapasitas_fkl_pemda_satuan")->nullable();
                $table->text("sat_kapasitas_fkl_pemda_ket")->nullable();
                $table->integer("sat_dana_investasi_non_pemerintah_tahun")->nullable();
                $table->double("sat_dana_investasi_non_pemerintah_nilai",20,3)->nullable();
                $table->string("sat_dana_investasi_non_pemerintah_satuan")->nullable();
                $table->text("sat_dana_investasi_non_pemerintah_ket")->nullable();
                $table->timestamps();

                $table->unique(['id','kode_daerah','kode_pdam','period_tahun','period_bulan_ahir']);




        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        Schema::dropIfExists('audit_sat');

    }
}
